### ISSUE TITLE
GMP.Integers.Set doesn’t handle heading “+"

### ISSUE THREAD

**Issue by simonjwright** [AdaCore/gnatcoll#1]
This program
```
with Ada.Text_IO; use Ada.Text_IO;
with GNATCOLL.GMP.Integers;
procedure Bignum is
   I : GNATCOLL.GMP.Integers.Big_Integer;
begin
   Put_Line ("setting -1");
   GNATCOLL.GMP.Integers.Set (I, "-1");
   Put_Line ("setting 1");
   GNATCOLL.GMP.Integers.Set (I, "1");
   Put_Line ("setting +1");
   GNATCOLL.GMP.Integers.Set (I, "+1");
   Put_Line ("done.");
end Bignum;
```
fails with
```
$ ./bignum 
setting -1
setting 1
setting +1

raised GNATCOLL.GMP.INTEGERS.FAILURE : gnatcoll-gmp-integers.adb:65
```

I think this may be down to a feature of gmplib? (5.1.3)

**Comment by briot** [comment]
> raised GNATCOLL.GMP.INTEGERS.FAILURE : gnatcoll-gmp-integers.adb:65
> 
> I think this may be down to a feature of gmplib? (5.1.3)

Indeed, the code in gnatcoll seems to be a direct binding to mpz_set_str.
The documentation of that function is pretty limited though, and does not indicate
whether this is expected or not:

<<<
Function: int mpz_set_str (mpz_t rop, const char *str, int base)
Set the value of rop from str, a null-terminated C string in base base. White space is allowed in the string, and is simply ignored.

The base may vary from 2 to 62, or if base is 0, then the leading characters are used: 0x and 0X for hexadecimal, 0b and 0B for binary, 0 for octal, or decimal otherwise.

For bases up to 36, case is ignored; upper-case and lower-case letters have the same value. For bases 37 to 62, upper-case letter represent the usual 10..35 while lower-case letter represent 36..61.

This function returns 0 if the entire string is a valid number in base base. Otherwise it returns -1.
>>>


I have updated the gnatcoll documentation, which seems to be about all we can do
here (I'd rather not add special handling for leading "+", possibly preceded by spaces, since
that would take us away from the semantics of libgmp, and possibly lead to conflicts in the
future).

Emmanuel
